### ISSUE TITLE
同步xml失败

### ISSUE THREAD

**Issue by zzq12345** [taksssss/tv#1]
增加一个
https://assets.livednow.com/epg.xml 
打开可以看，就是同步这个xml失败

**Comment by taksssss** [comment]
这个我之前加过，报403就没折腾了。我回头搞一下吧，修改UA貌似是能下载的。

**Comment by taksssss** [comment]
解决了，你试试吧。还是得用代理服务器才行，网站估计屏蔽github这边的ip了。
